----------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------
--
-- 	MEDIEVAL KINGDOMS 1212 - COMMON UI: UNIT INFORMATION LISTS
-- 	By: DETrooper
--
----------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------
-- This is kind of shit since I should probably import everything related to units from DB into lua tables
-- and then go from there, calculating the unit stats that way instead of manually inputting the numbers.

unit_info = {
	["mk_mio_t1_hospitaller_sergeant_spearmen"] = {["num_men"] = 160, ["upkeep"] = 174, ["unit_weight"] = "medium", ["unit_type"] = "att_inf_spear_land", ["tier"] = 1},
	["mk_mio_t1_templar_sergeant_spearmen"] = {["num_men"] = 160, ["upkeep"] = 174, ["unit_weight"] = "medium", ["unit_type"] = "att_inf_spear_land", ["tier"] = 1},
	["mk_mio_t1_hospitaller_knights_dismounted"] = {["num_men"] = 160, ["upkeep"] = 307, ["unit_weight"] = "heavy", ["unit_type"] = "att_inf_sword_land", ["tier"] = 1},
	["mk_mio_t1_templar_knights_dismounted"] = {["num_men"] = 160, ["upkeep"] = 307, ["unit_weight"] = "heavy", ["unit_type"] = "att_inf_sword_land", ["tier"] = 1},
	["mk_mio_t1_hospitaller_crossbowmen_sergeants"] = {["num_men"] = 130, ["upkeep"] = 222, ["unit_weight"] = "medium", ["unit_type"] = "att_inf_crossbow_land", ["tier"] = 1},
	["mk_mio_t1_templar_crossbowmen_sergeants"] = {["num_men"] = 130, ["upkeep"] = 222, ["unit_weight"] = "medium", ["unit_type"] = "att_inf_crossbow_land", ["tier"] = 1},
	["mk_mio_t1_hospitaller_mounted_sergeants"] = {["num_men"] = 80, ["upkeep"] = 274, ["unit_weight"] = "medium", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_hospitaller_knights"] = {["num_men"] = 80, ["upkeep"] = 463, ["unit_weight"] = "heavy", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_templar_mounted_sergeants"] = {["num_men"] = 80, ["upkeep"] = 274, ["unit_weight"] = "medium", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_templar_knights"] = {["num_men"] = 80, ["upkeep"] = 463, ["unit_weight"] = "heavy", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_teu_mounted_sergeants"] = {["num_men"] = 80, ["upkeep"] = 274, ["unit_weight"] = "medium", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_teu_sariantbruder"] = {["num_men"] = 80, ["upkeep"] = 319, ["unit_weight"] = "medium", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_teu_ritterbruder"] = {["num_men"] = 80, ["upkeep"] = 463, ["unit_weight"] = "heavy", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
};

unit_stats = {
	["mk_mio_t1_hospitaller_sergeant_spearmen"] = {["melee_attack"] = 34, ["weapon_damage"] = 29, ["charge_bonus"] = 15, ["melee_defence"] = 33, ["armour"] = 25, ["health"] = 100, ["morale"] = 35, ["speed"] = 30, ["missile_block_chance"] = 25, ["bonus_vs_cavalry"] = 12},
	["mk_mio_t1_templar_sergeant_spearmen"] = {["melee_attack"] = 34, ["weapon_damage"] = 29, ["charge_bonus"] = 15, ["melee_defence"] = 33, ["armour"] = 25, ["health"] = 100, ["morale"] = 35, ["speed"] = 30, ["missile_block_chance"] = 25, ["bonus_vs_cavalry"] = 12},
	["mk_mio_t1_hospitaller_knights_dismounted"] = {["melee_attack"] = 38, ["weapon_damage"] = 26, ["charge_bonus"] = 30, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 100, ["morale"] = 50, ["speed"] = 30, ["missile_block_chance"] = 40},
	["mk_mio_t1_templar_knights_dismounted"] = {["melee_attack"] = 38, ["weapon_damage"] = 26, ["charge_bonus"] = 30, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 100, ["morale"] = 50, ["speed"] = 30, ["missile_block_chance"] = 40},
	["mk_mio_t1_hospitaller_crossbowmen_sergeants"] = {["melee_attack"] = 30, ["weapon_damage"] = 26, ["melee_defence"] = 15, ["armour"] = 25, ["health"] = 100, ["morale"] = 35, ["speed"] = 30, ["missile_damage"] = 48, ["ammo"] = 30, ["reloading"] = 23, ["weapon_range"] = 145, ["accuracy"] = 15},
	["mk_mio_t1_templar_crossbowmen_sergeants"] = {["melee_attack"] = 30, ["weapon_damage"] = 26, ["melee_defence"] = 15, ["armour"] = 25, ["health"] = 100, ["morale"] = 35, ["speed"] = 30, ["missile_damage"] = 48, ["ammo"] = 30, ["reloading"] = 23, ["weapon_range"] = 145, ["accuracy"] = 15},
	["mk_mio_t1_hospitaller_mounted_sergeants"] = {["melee_attack"] = 30, ["weapon_damage"] = 29, ["charge_bonus"] = 95, ["melee_defence"] = 30, ["armour"] = 25, ["health"] = 150, ["morale"] = 35, ["speed"] = 90, ["missile_block_chance"] = 25},
	["mk_mio_t1_hospitaller_knights"] = {["melee_attack"] = 38, ["weapon_damage"] = 27, ["charge_bonus"] = 155, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 150, ["morale"] = 50, ["speed"] = 75, ["missile_block_chance"] = 40},
	["mk_mio_t1_templar_mounted_sergeants"] =  {["melee_attack"] = 30, ["weapon_damage"] = 29, ["charge_bonus"] = 95, ["melee_defence"] = 30, ["armour"] = 25, ["health"] = 150, ["morale"] = 35, ["speed"] = 90, ["missile_block_chance"] = 25},
	["mk_mio_t1_templar_knights"] = {["melee_attack"] = 38, ["weapon_damage"] = 27, ["charge_bonus"] = 155, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 150, ["morale"] = 50, ["speed"] = 75, ["missile_block_chance"] = 40},
	["mk_mio_t1_teu_mounted_sergeants"] = {["melee_attack"] = 30, ["weapon_damage"] = 29, ["charge_bonus"] = 95, ["melee_defence"] = 30, ["armour"] = 25, ["health"] = 150, ["morale"] = 35, ["speed"] = 90, ["missile_block_chance"] = 25},
	["mk_mio_t1_teu_sariantbruder"] = {["melee_attack"] = 35, ["weapon_damage"] = 29, ["charge_bonus"] = 95, ["melee_defence"] = 35, ["armour"] = 25, ["health"] = 150, ["morale"] = 50, ["speed"] = 90, ["missile_block_chance"] = 25},
	["mk_mio_t1_teu_ritterbruder"] = {["melee_attack"] = 38, ["weapon_damage"] = 27, ["charge_bonus"] = 155, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 150, ["morale"] = 50, ["speed"] = 75, ["missile_block_chance"] = 40},
};

unit_bullet_points = {
	["mk_mio_t1_hospitaller_sergeant_spearmen"] = {"positive|Доб. Шкода крізь облад.|", "negative|Пог. Броня|", "negative|Пог. Шанс захисту від стрільців|"},
	["mk_mio_t1_templar_sergeant_spearmen"] = {"positive|Доб. Шкода крізь облад.|", "negative|Пог. Броня|", "negative|Пог. Шанс захисту від стрільців|"},
	["mk_mio_t1_hospitaller_knights_dismounted"] = {"very_positive|Відм. Бойовий дух|", "very_negative|Дуж. пог. Шкода крізь облад.|", "positive|Доб. Броня|"},
	["mk_mio_t1_templar_knights_dismounted"] = {"very_positive|Відм. Бойовий дух|", "very_negative|Дуж. пог. Шкода крізь облад.|", "positive|Доб. Броня|"},
	["mk_mio_t1_hospitaller_crossbowmen_sergeants"] = {"very_negative|Дуж. пог. Шанс захисту від стрільців|", "positive|Висок. Боєприпаси|", "negative|Пл. Урон скв. досп.|"},
	["mk_mio_t1_templar_crossbowmen_sergeants"] = {"very_negative|Дуж. пог. Шанс захисту від стрільців|", "positive|Висок. Боєприпаси|", "negative|Пл. Урон скв. досп.|"},
	["mk_mio_t1_hospitaller_mounted_sergeants"] = {"positive|Висок. Здоров'я|", "positive|Доб. Посил. натиску|", "negative|Пог. Броня|"},
	["mk_mio_t1_hospitaller_knights"] = {"very_positive|Відм. Посил. натиску|", "very_positive|Відм. Бойовий дух|", "positive|Висок. Здоров'я|"},
	["mk_mio_t1_templar_mounted_sergeants"] = {"positive|Висок. Здоров'я|", "positive|Доб. Посил. натиску|", "negative|Пог. Броня|"},
	["mk_mio_t1_templar_knights"] = {"very_positive|Відм. Посил. натиску|", "very_positive|Відм. Бойовий дух|", "positive|Висок. Здоров'я|"},
	["mk_mio_t1_teu_mounted_sergeants"] = {"positive|Висок. Здоров'я|", "positive|Доб. Посил. натиску|", "negative|Пог. Броня|"},
	["mk_mio_t1_teu_sariantbruder"] = {"very_positive|Відм. Бойовий дух|", "positive|Висок. Здоров'я|", "positive|Доб. Посил. натиску|"},
	["mk_mio_t1_teu_ritterbruder"] = {"very_positive|Відм. Посил. натиску|", "very_positive|Відм. Бойовий дух|", "positive|Висок. Здоров'я|"}
};

unit_abilities = {
	["mk_mio_t1_hospitaller_sergeant_spearmen"] = {"form_hoplite_phalanx", "a_mp_test_7", "hide_forest"},
	["mk_mio_t1_templar_sergeant_spearmen"] = {"form_hoplite_phalanx", "a_mp_test_7", "hide_forest"},
	["mk_mio_t1_hospitaller_knights_dismounted"] = {"form_shield_wall", "a_mp_test_6", "disciplined", "hide_forest", "scare_immune"},
	["mk_mio_t1_templar_knights_dismounted"] = {"form_shield_wall", "a_mp_test_6", "disciplined", "hide_forest", "scare_immune"},
	["mk_mio_t1_hospitaller_crossbowmen_sergeants"] = {"a_mp_test_7", "mk_crossbow_early", "mk_crossbow_extended", "hide_forest"},
	["mk_mio_t1_templar_crossbowmen_sergeants"] = {"a_mp_test_7", "mk_crossbow_early", "mk_crossbow_extended", "hide_forest"},
	["mk_mio_t1_hospitaller_mounted_sergeants"] = {"a_mp_test_7", "hide_forest"},
	["mk_mio_t1_hospitaller_knights"] = {"form_wedge", "a_mp_test_7", "disciplined", "hide_forest", "scare_immune"},
	["mk_mio_t1_templar_mounted_sergeants"] = {"a_mp_test_7", "hide_forest"},
	["mk_mio_t1_templar_knights"] = {"form_wedge", "a_mp_test_7", "disciplined", "hide_forest", "scare_immune"},
	["mk_mio_t1_teu_mounted_sergeants"] = {"form_wedge", "a_mp_test_7", "hide_forest"},
	["mk_mio_t1_teu_sariantbruder"] = {"form_wedge", "a_mp_test_7", "disciplined", "hide_forest"},
	["mk_mio_t1_teu_ritterbruder"] = {"form_wedge", "a_mp_test_7", "disciplined", "hide_forest", "scare_immune"}
};

unit_stats_ordered = {"melee_attack", "weapon_damage", "charge_bonus", "melee_defence", "armour", "health", "morale", "speed", "missile_block_chance", "missile_damage", "ammo", "reloading", "weapon_range", "accuracy", "bonus_vs_cavalry"};

ui_unit_groupings = {
	["art_fix"] = {"Стаціонарна далекобійна машина", "Декілька стаціонарних метальних машин можуть завдати нищівної шкоди, у ближньому ж бою вони вкрай слабкі."},
	["art_fld"] = {"Далекобійна машина", "Метальні машини б'ють на великі відстані та завдають величезної шкоди, їх навіть можна повільно рухати по полю бою, однак вони дуже слабкі в ближньому бою."},
	["art_siege"] = {"Облогові машини", "Величезні облогові машини спеціально створені для того, щоб зносити стіни і вибивати ворота."},
	["att_art_field_land"] = {"Метальні машини", "Метальні машини б'ють на великі відстані і завдають величезної шкоди, їх навіть можна повільно рухати по полю бою, проте вони дуже слабкі в ближньому бою."},
	["att_art_field_naval"] = {"Мет. машини", "Метальні машини б'ють на великі відстані і завдають величезної шкоди, їх навіть можна повільно рухати по полю бою, проте вони дуже слабкі в ближньому бою."},
	["att_art_scorpio"] = {"Скорпіон", "Метальні машини б'ють на великі відстані і завдають величезної шкоди, їх навіть можна повільно рухати по полю бою, проте вони дуже слабкі у ближньому бою."},
	["att_cav_bow_land"] = {"Кінні стрільці", "Ці кінні лучники швидко рухаються, далеко стріляють і приносять ворогу багато лиха, проте стають слабкі, вступивши в ближній бій." },
	["att_cav_crossbow_land"] = {"Кіннота з арбалетами", "Ці кінні арбалетники швидко рухаються, влучно стріляють на середніх дистанціях і приносять ворогу безліч лиха, проте стають слабкими, вступивши в ближній бій." },
	["att_cav_elephant_land"] = {"Слони", "Ніхто, як слон, не розметає ворожі ряди. Найкращий спосіб зупинити слонів - закидати їх палаючими снарядами і дротиками."},
	["att_cav_javelin_land"] = {"Кінні застрільники", "Ці кінні застрільники швидко рухаються, влучно стріляють на ближніх дистанціях і приносять ворогу багато лиха, але стають слабкі, вступивши в рукопашний бій." },
	["att_cav_melee_land"] = {"Кіннота б. бою", "Це легкі, маневрені вершники. Утім, навіть щити не захистять їх від сильніших військ."},
	["att_cav_shock_land"] = {"Ударна кіннота", "Вдаривши з флангу або в тил, вони розтрощать будь-яку піхоту."},
	["att_inf_axe_land"] = {"Піхота з сокирами", "Передовий загін, навчений рукопашному бою."},
	["att_inf_axe_marine"] = {"Піхота з сокирами", "Передовий загін, навчений рукопашному бою."},
	["att_inf_axe_naval"] = {"Штурмовий корабель", "Передовий загін, навчений рукопашному бою."},
	["att_inf_bow_land"] = {"Піхота з луками", "Ці загони підтримують піхоту здалеку, але в ближньому бою ні на що не здатні."},
	["att_inf_bow_marine"] = {"Піхота з луками", "Ці загони підтримують піхоту здалеку, але в ближньому бою ні на що не здатні."},
	["att_inf_bow_naval"] = {"Корабель з лучниками", "Ці загони підтримують піхоту здалеку, але в ближньому бою ні на що не здатні."},
	["att_inf_crossbow_land"] = {"Піхота з арбалетами", "Стрільці, здатні пробити будь-яку броню на середніх дистанціях, але вкрай повільно перезаряджають свою зброю."},
	["att_inf_crossbow_marine"] = {"Піхота з арбалетами", "Стрільці, здатні пробити будь-яку броню на середніх дистанціях, але які вкрай повільно перезаряджають свою зброю." },
	["att_inf_crossbow_naval"] = {"Корабель з арбалетчиками", "Стрільці, здатні пробити будь-яку броню на середніх дистанціях, але вкрай повільно перезаряджають свою зброю." },
	["att_inf_gun_land"] = {"Піхота з вогнепал. зброєю", "Вогнепальні загони, здатні пробити будь-яку броню на середніх дистанціях, але вкрай повільно перезаряджають свою зброю." },
	["att_inf_javelin_land"] = {"Застрільники", "Стрільці, здатні завдати винятково високої шкоди на коротких дистанціях."},
	["att_inf_javelin_marine"] = {"Застрільники", "Стрільці, здатні завдати винятково високої шкоди на коротких дистанціях."},
	["att_inf_javelin_naval"] = {"Застрільники", "Стрільці, здатні завдати винятково високої шкоди на коротких дистанціях."},
	["att_inf_pike_land"] = {"Піхота з піками", "Завдяки довгим пікам вони майже незламні при атаці в лоб, але вразливі, якщо зайти до них у фланг. Виключно ефективні в бою проти кінноти."},
	["att_inf_polearm_land"] = {"Піхота з древковою зброєю", "Завдяки древковій зброї вони майже незламні при атаці в лоб, але вразливі, якщо зайти до них у фланг. Виключно ефективні в бою проти кінноти."},
	["att_inf_polearm_shock_land"] = {"Ударна піхота", "Суворі солдати передових шеренг, озброєні відмінною бронебійною зброєю."},
	["att_inf_sling_land"] = {"Пращники", "Стрільці для середніх дистанцій, здатні дуже швидко перезаряджати свою зброю."},
	["att_inf_sling_marine"] = {"Пращники", "Стрільці для середніх дистанцій, здатні дуже швидко перезаряджати свою зброю."},
	["att_inf_sling_naval"] = {"Пращники", "Стрільці для середніх дистанцій, здатні дуже швидко перезаряджати свою зброю."},
	["att_inf_spear_bow_land"] = {"Списоносна піх. з луками", "Солдати 'подвійного призначення', здатні як воювати в передніх лавах, так і обстрілювати супротивника здалеку."},
	["att_inf_spear_land"] = {"Піхота зі списами", "Важкі, добре захищені щитники відмінно витримують навіть удар кінноти."},
	["att_inf_sword_bow_land"] = {"Стрілецька піхота бл. бою", "Солдати 'подвійного призначення', здатні як битися в передніх лавах, так і обстрілювати противника здалеку."},
	["att_inf_sword_land"] = {"Піхота ближнього бою", "Бійці першої лінії завжди готові до рукопашної."},
	["att_inf_sword_marine"] = {"Піхота ближнього бою", "Бійці першої лінії завжди готові до рукопашної."},
	["att_inf_sword_naval"] = {"Корабель ближнього бою", "Бійці першої лінії завжди готові до рукопашної."},
	["att_special_fireship_naval"] = {"Запал. корабель", "Може підпалювати інші кораблі."},
	["att_special_greek_fire_land"] = {"Метальники грецьк. вогню", "Вивергаючи полум'я, яке неможливо погасити, ці загони здатні спалити будь-якого супротивника вщент, прирікаючи того на болісну смерть. Однак, вони нечисленні і не здатні взяти з собою велику кількість палива."},
	["att_special_grenade_land"] = {"Метальники нафти", "Цей загін може метати в супротивника посудини з нафтою, що завдають нищівної шкоди, але дуже вразливий через нечисленність."},
	["att_special_grenade_marine"] = {"Метальники нафти", "Цей загін може метати в супротивника посудини з нафтою, що завдають нищівної шкоди, але дуже вразливий через нечисленність."},
	["att_special_grenade_naval"] = {"Метальники нафти", "Цей загін може метати в супротивника посудини з нафтою, що завдають нищівної шкоди, але дуже вразливий через нечисленність."},
	["att_special_ram_naval"] = {"Таранний корабель", "Повний вперед!"},
	["att_special_transportship_naval"] = {"Вантажний корабель", "Повільні, але місткі, вони відмінно справляються зі своїм завданням. Головне - пам'ятати, що це не бойові кораблі."},
	["att_special_wardog_land"] = {"Бойові пси", "Бойові пси становлять серйозну загрозу для воїнів у легких обладунках."},
	["carroccio"] = {"Карроччо", "."},
	["cav_mel"] = {"Кіннота б. бою", "Це легкі, маневрені вершники. Утім, навіть щити не захистять їх від сильніших військ."},
	["cav_mis"] = {"Стрілецька кіннота", "Кінні лучники швидко рухаються, далеко стріляють і приносять ворогу багато лиха, проте стають слабкими, вступивши в ближній бій."},
	["cav_shk"] = {"Ударна кіннота", "Ударивши з флангу або в тил, вони розтрощать будь-яку піхоту."},
	["chariot"] = {"Колісниці", "Стрімкі загони з великим радіусом розвороту. Прорізають ряди противника як масло, але загрузнувши в ближньому бою, стають вразливими."},
	["com"] = {"Командування", "Невеликі загони, які захищають полководця в пеклі бою."},
	["elph"] = {"Слони", "Ніхто краще за слона не розметає ворожі ряди. Найкращий спосіб зупинити слонів - закидати їх палаючими снарядами і дротиками."},
	["inf_mel"] = {"Піхота ближнього бою", "Бійці першої лінії завжди готові до рукопашної."},
	["inf_mis"] = {"Стрілецька піхота", "Ці загони підтримують піхоту здалеку, але в ближньому бою ні на що не здатні."},
	["inf_pik"] = {"Піхота з піками", "Завдяки довгим пікам вони майже незламні при атаці в лоб, але вразливі, якщо зайти до них у фланг. Виключно ефективні в бою проти кінноти."},
	["inf_sling"] = {"Пращники", "placeholder"},
	["inf_spr"] = {"Піхота зі списами", "Важкі, добре захищені щитники відмінно витримують навіть удар кінноти."},
	["ltd_hussite_warwagon"] = {"Бойовий візок", "."},
	["ltd_medieval_tent"] = {"Намет", "."},
	["shp_art"] = {"Корабель з далекобійними машинами", "Здалеку ці кораблі можуть завдати важкої шкоди, але проти тарана або абордажної команди вони безсилі."},
	["shp_mel"] = {"Корабель ближнього бою", "Ідеальний абордажний корабель. Щоб досягти успіху, йому спершу треба нагнати жертву."},
	["shp_mis"] = {"Стрілецький корабель", "Вони можуть обрушити на ворога град стріл і снарядів, але в ближньому бою вони беззахисні."},
	["shp_trn"] = {"Вантажний корабель", "Повільні, але місткі, вони відмінно справляються зі своїм завданням. Головне - пам'ятати, що це не бойові кораблі."},
	["spcl"] = {"Особлива бойова одиниця", "Здивуйте ваших ворогів дикими тваринами."},
};

ui_unit_stats = {
	["scalar_bracing"] = {"Стійкість до натиску", "Загальна вага всіх воїнів у загоні.", 1000},
	["scalar_entity_acceleration_modifier"] = {"Прискорення", "Темп, в якому бойова одиниця набирає швидкість.", 100},
	["scalar_entity_charge_speed_modifier"] = {"Швидкість натиску", "Швидкість, яку розвиває загін на фінальному етапі натиску.", 100},
	["scalar_entity_deceleration_modifier"] = {"Уповільнення", "Темп, у якому бойова одиниця знижує швидкість.", 100},
	["scalar_spotting_range"] = {"Дальність огляду", "Змінює відстань, на якій загін за замовчуванням помічає тих, хто сховався.", 100},
	["stat_accuracy"] = {"Точність", "Імовірність влучання в противника під час стрільби.", 75},
	["stat_ammo"] = {"Боєприпаси", "Число боєприпасів, які цей загін може взяти на битву.||Коли ці боєприпаси закінчаться, загону доведеться вступити в ближній бій.||Після бою боєприпаси повністю відновлюються.", 50},
	["stat_armour"] = {"Броня", "Стійкість загону до обстрілу й атак у ближньому бою.", 120},
	["stat_attack"] = {"Атака", "Наступальні можливості загону", 100},
	["stat_bonus_vs_cavalry"] = {"Атака проти кінноти", "Перевага, яку отримує загін, б'ючись у ближньому бою проти кінноти і слонів.", 60},
	["stat_bonus_vs_elephants"] = {"Атака проти слонів", "Бонус, який отримує загін, борючись у ближньому бою проти слонів.", 60},
	["stat_bonus_vs_infantry"] = {"Атака проти піхоти", "Бонус, який отримує загін, б'ючись у ближньому бою проти піхоти.", 60},
	["stat_capture_power"] = {"Ефективність захоплення", "Швидкість, з якою загін захоплює точки в битвах за поселення.", 25},
	["stat_charge_bonus"] = {"Посилення натиску", "Величина, на яку під час натиску підвищується шкода й ефективність атаки в ближньому бою. Не впливає на силу натиску.", 300},
	["stat_defence"] = {"Захист", "Оборонні можливості загону", 100},
	["stat_first_strike"] = {"Перший удар", "Визначає, хто першим завдає удару в бою.", 100},
	["stat_health"] = {"Здоров'я", "Визначає, скільки влучень може витримати загін, виходячи з його броні та захисту в ближньому бою.", 350},
	["stat_hiding"] = {"Маскування", "Уміння загону ховатися.", 100},
	["stat_melee_attack"] = {"Ближній бій", "Шанс бійців цього загону поцілити по ворогу в ближньому бою.||Загартовані в боях бійці отримують все більше досвіду, підвищуючи свої навички та вміння.", 75},
	["stat_melee_damage_ap"] = {"Урон скв. обладунки", "Урон броні в ближньому бою", 25},
	["stat_melee_damage_base"] = {"Базова шкода в ближньому бою", "Основна шкода в ближньому бою", 75},
	["stat_melee_defence"] = {"Захист у ближ. бою", "Шанс влучання по бійцях загону в ближньому бою.||Цей параметр відповідає тільки за ближній бій, але не за захист від снарядів!", 75},
	["stat_men_count"] = {"Чисельність", "Чисельність загону за замовчуванням.", 120},
	["stat_missile_block_chance"] = {"Шанс захисту від стрільців", "Шанс відбиття щитом шкоди від стрілецької зброї (за винятком далекобійних машин). (%)", 100},
	["stat_missile_damage"] = {"Пошкодження снарядами", "Постріли можуть наносити три види шкоди: базову, крізь обладунки та від вибуху.||Пошкодження крізь обладунки наноситься завжди, два інших види шкоди можуть бути заблоковані обладунками.||Пошкодження від вибуху має певний радіус ураження.", 100},
	["stat_missile_damage_ap"] = {"Пошкодження крізь обладунки", "Пробиття обладунків у дальньому бою", 50},
	["stat_missile_damage_base"] = {"Базова шкода від пострілів", "Базова шкода в дальньому бою", 100},
	["stat_morale"] = {"Бойовий дух", "Загін з високим бойовим духом з меншою ймовірністю біжить перед лицем небезпеки. Бойовий дух зростає в міру участі в битвах.", 75},
	["stat_reloading"] = {"Скорострільність", "Швидкість стрільби загону.||Швидкість зростає з досвідом.", 100},
	["stat_remaining_ammo"] = {"Додані боєприпаси", "Поповнення боєзапасу кораблів.", 20},
	["stat_shield_armour"] = {"Броня щита", "Пошкодження зменшено завдяки щиту.", 75},
	["stat_shield_defence"] = {"Ефективність щитів", "Перевага в захисті або ухилянні, що дається щитом.", 45},
	["stat_ship_douse_fire"] = {"Гасіння пожежі", "Гасіння пожежі", 10},
	["stat_ship_health"] = {"Міцність", "Міцність", 2500},
	["stat_ship_health_fire"] = {"Захист від вогню", "Втрата від вогню, яку може витримати корабель, перш ніж загориться.", 2000},
	["stat_ship_move_speed"] = {"Швидкість", "Швидкість руху кораблів.", 100},
	["stat_speed"] = {"Швидкість", "Швидкість, з якою загін переміщається по полю бою.", 120},
	["stat_spotting"] = {"Огляд", "Відстань, на якій бойова одиниця може виявляти ворогів.", 1000},
	["stat_weapon_damage"] = {"Збиток у ближ. бою", "Збиток, що завдається зброєю загону: базовий і крізь обладунки.||Збиток крізь обладунки наноситься завжди, від базової шкоди обладунки можуть захистити.", 75},
	["stat_weapon_range"] = {"Дальність", "Велика далекобійність дозволяє вражати противника здалеку, але на невеликі відстані зброя все одно б'є точніше.", 500}
}

unit_weights_texts = {
	["very_light"] = "Дуже легк.",
	["light"] = "Легк.",
	["medium"] = "Середн.",
	["heavy"] = "Важк.",
	["very_heavy"] = "Дуже важк.",
	["super_heavy"] = "Надзвичайно важк."
};
